FROM node:18

# Create app directory
WORKDIR /app

# Copy package.json and install deps
COPY package*.json ./
RUN npm install

# Copy the rest of the code
COPY . .

# Expose default dev server port
EXPOSE 3000

# Start the frontend dev server
CMD ["npm", "start"]
