# Use official Node.js image
FROM node:18

# Create app directory
WORKDIR /app

# Copy source code
COPY . .

# Install dependencies
RUN npm install

# Expose backend port
EXPOSE 5000

# Start the server
CMD ["node", "express.js"]
