# Use Node base image
FROM node:18

# Create app directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the code (including express.js, score.js, CSV, etc.)
COPY . .

# Expose backend port
EXPOSE 5000

# Start the server
CMD ["node", "express.js"]
